server:
  port: 8080

spring:
  application:
    name: second-score-server
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/second_score?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 2004
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      username: root
      password:
      database: 2
      timeout: 5s
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 5MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

knife4j:
  enable: true
  setting:
    language: zh_cn

jwt:
  secret: secondscore-secondscore-secondscore-secondscore-2026
  expiration-minutes: 120

app:
  upload:
    base-dir: uploads
    avatar-sub-dir: avatar

logging:
  level:
    com.secondscore: info
